# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protobuf/api.proto\"\xb1\x01\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1f\n\x07sensors\x18\x03 \x03(\x0b\x32\x0e.Device.Sensor\x1a\"\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x1aH\n\x08\x41\x63tuator\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a\"\n\rActuatorState\x12\x11\n\tstateName\x18\x01 \x01(\t\"&\n\nDeviceList\x12\x18\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x07.DeviceB\x1e\n\x17\x62r.ufc.smarthome.modelsB\x03\x41pib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027br.ufc.smarthome.modelsB\003Api'
  _DEVICE._serialized_start=23
  _DEVICE._serialized_end=200
  _DEVICE_SENSOR._serialized_start=92
  _DEVICE_SENSOR._serialized_end=126
  _DEVICE_ACTUATOR._serialized_start=128
  _DEVICE_ACTUATOR._serialized_end=200
  _DEVICE_ACTUATOR_ACTUATORSTATE._serialized_start=166
  _DEVICE_ACTUATOR_ACTUATORSTATE._serialized_end=200
  _DEVICELIST._serialized_start=202
  _DEVICELIST._serialized_end=240
# @@protoc_insertion_point(module_scope)
