# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/iot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protobuf/iot.proto\"\xe4\x01\n\x12JoinRequestMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x07sensors\x18\x02 \x03(\x0b\x32\x1a.JoinRequestMessage.Sensor\x12/\n\tactuators\x18\x03 \x03(\x0b\x32\x1c.JoinRequestMessage.Actuator\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\t\x1a\"\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a$\n\x08\x41\x63tuator\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"!\n\x13JoinResponseMessage\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.iot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINREQUESTMESSAGE._serialized_start=23
  _JOINREQUESTMESSAGE._serialized_end=251
  _JOINREQUESTMESSAGE_SENSOR._serialized_start=179
  _JOINREQUESTMESSAGE_SENSOR._serialized_end=213
  _JOINREQUESTMESSAGE_ACTUATOR._serialized_start=215
  _JOINREQUESTMESSAGE_ACTUATOR._serialized_end=251
  _JOINRESPONSEMESSAGE._serialized_start=253
  _JOINRESPONSEMESSAGE._serialized_end=286
# @@protoc_insertion_point(module_scope)
