# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tiot.proto\"\x07\n\x05\x45mpty\"\x1e\n\x10ShutdownResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"#\n\x15ToggleActuatorRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x16ToggleActuatorResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32x\n\rDeviceService\x12\"\n\x0eShutdownDevice\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x43\n\x0eToggleActuator\x12\x16.ToggleActuatorRequest\x1a\x17.ToggleActuatorResponse\"\x00\x42.\n\'br.gov.ufc.homeassistantserver.servicesB\x03Iotb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'br.gov.ufc.homeassistantserver.servicesB\003Iot'
  _EMPTY._serialized_start=13
  _EMPTY._serialized_end=20
  _SHUTDOWNRESPONSE._serialized_start=22
  _SHUTDOWNRESPONSE._serialized_end=52
  _TOGGLEACTUATORREQUEST._serialized_start=54
  _TOGGLEACTUATORREQUEST._serialized_end=89
  _TOGGLEACTUATORRESPONSE._serialized_start=91
  _TOGGLEACTUATORRESPONSE._serialized_end=127
  _DEVICESERVICE._serialized_start=129
  _DEVICESERVICE._serialized_end=249
# @@protoc_insertion_point(module_scope)
